version: "3.3"
services:
  api:
    container_name: "api"
    build: "./api"
    ports:
      - "8080:8080"
    volumes:
      - "./api:/go/src/app"
    depends_on:
      - "mongodb"
  web:
    container_name: "web"
    image: "nginx:latest"
    ports:
      - "8081:80"
    volumes:
      - "./web:/usr/share/nginx/html"
    depends_on:
      - "api"
  mongodb:
    container_name: "mongodb"
    build:
      context: ./mongo
      dockerfile: Dockerfile
    ports:
      - "27100:27017"
